version: "3.3"
services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: devenv/.env
        volumes:
            - ./devenv/plugins:/var/www/html/wp-content/plugins
            - ./devenv/languages:/var/www/html/wp-content/languages
            - ./tmp/wp-content-uploads:/var/www/html/wp-content/uploads
            - ./tmp/http-logs:/var/log/apache2
            - ./src:/var/www/html/wp-content/plugins/simple-login-history
    db:
        image: mysql:latest
        env_file: devenv/.env
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        env_file: devenv/.env
        links:
            - db
        ports:
             - 8080:80
        volumes:
             - ./tmp/phpmyadmin-sessions:/sessions
    smtp:
        image: schickling/mailcatcher
        container_name: smtp
        env_file: devenv/.env
        ports:
             - 1080:1080
             - 1025:1025

volumes:
    db-data:
        driver: local

